<CustBoxLayout@BoxLayout>:
    orientation: "horizontal"
    spacing: 0.5

<CustButton@Button>:
    background_normal: ""
    background_color: (0.505, 0.494, 0.505,1)
    color: 0,0,0,1

<OrangeButton@CustButton>
    background_color: 1, 0.016, 1, 1
    color: 1,1,1,1


<CalculatorLayout>:
    spacing: 0.5
    orientation: "vertical"
    display: display
    TextInput:
        id: display
        text: ""
        background_normal: ""
        background_color: (0.364, 0.635, 0.356,1)
        font_size: 30
        foreground_color: 1,1,1,1
        size_hint_y: 1.5
    CustBoxLayout:
        CustButton:
            text: "AC"
            on_press: display.text = ""
        CustButton:
            text: "("
            on_press: display.text += self.text
        CustButton:
            text: ")"
            on_press: display.text += self.text
        OrangeButton:
            text: "÷"
            on_press: root.calculate()
    CustBoxLayout:
        CustButton:
            text: "7"
            on_press: display.text += self.text
        CustButton:
            text: "8"
            on_press: display.text += self.text
        CustButton:
            text: "9"
            on_press: display.text += self.text
        OrangeButton:
            text: "x"
            on_press: root.divide()
    CustBoxLayout:
        CustButton:
            text: "4"
            on_press: display.text += self.text
        CustButton:
            text: "5"
            on_press: display.text += self.text
        CustButton:
            text: "6"
            on_press: display.text += self.text
        OrangeButton:
            text: "-"
            on_press: root.calculate()
    CustBoxLayout:
        CustButton:
            text: "1"
            on_press: display.text += self.text
        CustButton:
            text: "2"
            on_press: display.text += self.text
        CustButton:
            text: "3"
            on_press: display.text += self.text
        OrangeButton:
            text: "+"
            on_press: display.text += self.text
    CustBoxLayout:
        CustButton:
            text: "0"
            on_press: display.text += self.text
            size_hint_x: 2
        CustButton:
            text: "."
            on_press: display.text += self.text
        OrangeButton:
            text: "="
            on_press: root.calculate()

